### ISSUE TITLE
 about the use of macsim sst

### ISSUE THREAD

**Issue by GFLY-PAPER** [gthparch/macsim#28]
l use sst to connect macsim, I noticed "ifdef USING_SST" in macsim code , but I found no place defined USING_SST, I tried to print USING_SST,the result is empty, could you tell me how to define the USING_SST,It would be better if you give an example. 
 thanks!

**Comment by hyojongk** [comment]
USING_SST is only defined if you use macsim as an SST component (Makefile.am)
