### ISSUE TITLE
IARG_BRANCH_TARGET_ADDR is invalid for XBEGIN and XEND

### ISSUE THREAD

**Issue by hadibrais** [gthparch/macsim#33]
The INS_IsControlFlow function is called in the [instrument](https://github.com/gthparch/macsim/blob/75ee2b492e2405d8801e017df1f159927f58900d/tools/x86_trace_generator/trace_generator.cpp#L885) function to check whether the IARG_BRANCH_TARGET_ADDR argument is valid for the instruction. However, there are two instructions for which INS_IsControlFlow returns true but IARG_BRANCH_TARGET_ADDR is invalid. These instructions include XBEGIN and XEND. Therefore the code should be changed to:

```
if (INS_IsControlFlow(ins) && !INS_IsXend(ins) && !INS_IsXbegin(ins))
{
...
}
```

Credit goes to Divya Praneetha for stumbling upon this bug.

**Comment by hyesoon** [comment]
Thanks for the information. Can you share a source code example that triggered this problem?

**Comment by hadibrais** [comment]
Any program that includes these instructions. For example:

```
#include <immintrin.h>

int main(void) {
        int status;
        if ((status = _xbegin()) == _XBEGIN_STARTED) { 
        	_xend();
        }
        else { }
        return 0;
}
```
This can be compiled with gcc 4.8 or later with the -mrtm option. It can be executed on a processor that supports Intel's RTM, such as a relatively modern Intel server processor.
