### ISSUE TITLE
GPU traces with previous version of MacSim?

### ISSUE THREAD

**Issue by rezamirosanlou** [gthparch/macsim#39]
I received the Parboil and also the GraphBig-10K traces. I tried to run some tests to see if I would be able to run with MacSim and found that my MacSim version is not able to read the traces (the traces that I have are version 14). Just to clarify, I am using a MacSim version 1.2. However, I noticed that the version of the traces (14), only works with the newer release of the MacSim. I am just wondering is there any workaround that enable older MacSim (version 1.2 to be specific) to work with the traces that Sam handed to me?

For example, in the mri-q benchmark, I modified the kernel_config.txt to be:
-1 newptx
/trace2/ptx_jun2016/parboil_jul16/mri-q/small/_Z17ComputePhiMag_GPUPfS_S_i_0/Trace.txt
/trace2/ptx_jun2016/parboil_jul16/mri-q/small/_Z12ComputeQ_GPUiiPfS_S_S_S__0/Trace.txt

and also I modified the beginning of Trace.txt files as follows:
1024 newptx 6 
and 
16 newptx 3

Specifically, I receive the following when trying the traces version 14 with my MacSim:

src/trace_read.cc:1599: ASSERT FAILED (I=27  C=17152):  temp_num_req > 0
src/trace_read.cc:1599: ASSERT FAILED (I=27  C=17152):  size:0 max:64 num:0 type:2 num:1

Can you please advise?

**Comment by hyesoon** [comment]
Unfortunately, we don't provide backward compatibility for trace formats.  I don't remember the details that have been changed from the previous version of GPU traces (which was back in 2015). I believe the way kernel_config.txt is formed (which is relatively easy to fix with a script) and the register id/opcode ids. In macsim, the register ids/opcode ids are based on enumerators so it would be hard to convert back to the old trace format.  The efforts of just porting new trace format are probably easier. Or porting your code to a newer macsim would be probably more desirable.

**Comment by rezamirosanlou** [comment]
I was able to fix the issue by hooking up our simulator to the latest version of macsim; therefore, the issue has been resolved. 
Thanks for the time.
