### ISSUE TITLE
error while compiling macsim with SST

### ISSUE THREAD

**Issue by saurabhgangurde** [gthparch/macsim#7]
I'm getting following error while trying to compile macsim with sst.

##################################################################
make[6]: Entering directory '/mnt/New_Volume1/Acads/DDP/simulators/SST/src/sstelements-8.0.0/sst-elements-library-8.0.0/src/sst/elements/macsim'
  CXX      macsimComponent.lo
macsimComponent.cpp:6:44: fatal error: sst/core/serialization/element.h: No such file or directory
 #include <sst/core/serialization/element.h>

compilation terminated.
##################################################################

I'm using following commands:
./autogen.sh
./configure --prefix=$SST_HOME --with-boost=$BOOST_HOME
make && make install

Please help.

**Comment by matianyun** [comment]
how do you solve that?
